// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zayphjxnkplzwworctic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheXBoanhua3Bsend3b3JjdGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjkxMzcsImV4cCI6MjA2MjAwNTEzN30.KSjEVJfllr7LfaFxyIqgy99kGaWiHrYAzlUjLIzsOhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);